config/routes.rb
Generator::Application.routes.draw do
  resources :rules

  get "rules/index"
  root :to => "rules#index"

end

app/models/rule.rb
class Rule < ActiveRecord::Base
  attr_accessible :buildingDamage, :chem, :dalayed, :dead, :elec, :fire, :gas, :immediate, :minor, :nFeedback, :nMediaType, :name, :pFeedback, :pMediaType, :road, :roomNo, :trapped, :water, :when
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rules }
    end
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
    @rule = Rule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/new
  # GET /rules/new.json
  def new
    @rule = Rule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/1/edit
  def edit
    @rule = Rule.find(params[:id])
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(params[:rule])

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render json: @rule, status: :created, location: @rule }
      else
        format.html { render action: "new" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rules/1
  # PUT /rules/1.json
  def update
    @rule = Rule.find(params[:id])

    respond_to do |format|
      if @rule.update_attributes(params[:rule])
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule = Rule.find(params[:id])
    @rule.destroy

    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rules_helper.rb
module RulesHelper
  
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>

<body onload="prepare();">    
    
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <!--Sidebar content-->
          <button onclick="refreshList()" class="btn btn-primary">Refresh</button>
          <table class="table table-striped" id="ruleList">
            <tr>
                <td>RoomId</td>
                <td>When</td>
            </tr>
          </table>
      </div>
      <div class="span10">
        <div class="form-inline" > 
            <h4><i class="icon-pencil"></i>
                Add a new rule
            </h4>
        </div>
        <div class="form-inline" >        
            <label>Room Number</label>
            <input type="text" id="room">            
        </div>

        <div class="form-inline">        
            <label>When</label>
            <select id="when" class="span2">
                <option value="Enter" >Enter</option>
                <option value="Leave">Leave</option>
                <option value="90s">90s</option>              
            </select>
        </div>        
    
    <div class="span2" style="background-color:#EEE">
        <H5>People</H5>
        <div class="form-inline" >        
            <label>Minor</label>
            <input type="text" id="minor">            
        </div>
        <div class="form-inline" >        
            <label>Delayed</label>
            <input type="text" id="delayed">            
        </div>
        <div class="form-inline" >        
            <label>Immediate</label>
            <input type="text" id="immediate">            
        </div>
        <div class="form-inline" >        
            <label>Dead</label>
            <input type="text" id="dead">            
        </div>
        <div class="form-inline" >        
            <label>Trapped</label>
            <input type="text" id="trapped">            
        </div>
    </div>

    <div class="span2">
        <H5>Hazard</H5>
        <div class="form-inline" >        
            <label>Gas Leak</label>
            <input name="Hazard" type="checkbox" id="gas">            
        </div>
        <div class="form-inline" >        
            <label>Water Leak</label>
            <input name="Hazard" type="checkbox" id="water">            
        </div>
        <div class="form-inline" >        
            <label>Electric</label>
            <input name="Hazard" type="checkbox" id="elec">            
        </div>
        <div class="form-inline" >        
            <label>Chemical</label>
            <input name="Hazard" type="checkbox" id="chem">            
        </div>
    </div>

    <div class="span2" style="background-color:#EEE">
        <H5>Building Damage</H5>        
        <div class="form-inline" >        
            <label>None</label>
            <input name="Building Damage" type="radio" id="bd_none">            
        </div>
        <div class="form-inline" >        
            <label>Light</label>
            <input name="Building Damage" type="radio" id="bd_light">            
        </div>
        <div class="form-inline" >        
            <label>Moderate</label>
            <input name="Building Damage" type="radio" id="bd_moderate">            
        </div>
        <div class="form-inline" >        
            <label>Heavy</label>
            <input name="Building Damage" type="radio" id="bd_heavy">            
        </div>
    </div>

    <div class="span2">
        <H5>Fire</H5>
        <div class="form-inline" >        
            <label>None</label>
            <input name="Fire" type="radio" id="fire_none">            
        </div>
        <div class="form-inline" >        
            <label>Smoke</label>
            <input name="Fire" type="radio" id="fire_smoke">            
        </div>
        <div class="form-inline" >        
            <label>Burning</label>
            <input name="Fire" type="radio" id="fire_burning">            
        </div>
        <div class="form-inline" >        
            <label>Out</label>
            <input name="Fire" type="radio" id="fire_out">            
        </div>
    </div>

    <div class="span3" style="background-color:#EEE">
        <H5>Road Access</H5>
        <div class="form-inline" >        
            <label>Unobstructed</label>
            <input name="Road Access" type="radio" id="unobstructed">            
        </div>
        <div class="form-inline" >        
            <label>One Lane Open</label>
            <input name="Road Access" type="radio" id="oneLane">            
        </div>
        <div class="form-inline" >        
            <label>Blocked, Cycles Only</label>
            <input name="Road Access" type="radio" id="cyclesOnly">            
        </div>
        <div class="form-inline" >        
            <label>Blocked, Walk-in Only</label>
            <input name="Road Access" type="radio" id="walkOnly">            
        </div>
    </div>
    
    <div class="span10">     

        <label>Media Type</label>
        <select id="pMediaType" class="span2">
            <option value="Picture">Picture</option>
            <option value="Video">Video</option>                   
        </select>
        <label>Positive Feedback</label>
        <textarea id="pFeedBack" class="span8"></textarea>

        <label>Media Type</label>
        <select id="nMediaType" class="span2">
            <option value="Picture">Picture</option>
            <option value="Video">Video</option>                   
        </select>
        <label>Negative Feedback</label>
        <textarea id="nFeedBack" class="span8"></textarea>
        <br></br>
        <button onclick="submitRule()" class="btn btn-success">Submit</button>
        <br></br>
    </div>
</div>    
</div>
</div>
</div>

<script src="js/bootstrap-button.js"></script>
<script>
function refreshList() {
    var Rules = Parse.Object.extend("Rules5");
    var query = new Parse.Query(Rules);
    query.exists("RoomId");
    query.find({
      success: function(results) {
        var table = document.getElementById("ruleList");                
        for(var i = table.rows.length - 1; i > 0; i--)
        {
            table.deleteRow(i);
        }       
        for(var i=0; i<results.length; i++){
            var tr = document.createElement("tr");
            var td1 = document.createElement("td");            
            td1.appendChild(document.createTextNode(results[i].get("RoomId")));
            var td2 = document.createElement("td");                        
            td2.appendChild(document.createTextNode(results[i].get("When")));              
            tr.appendChild(td1);
            tr.appendChild(td2);
            table.appendChild(tr);
        }        
    },
    error: function(error) {
        alert("Error: " + error.code + " " + error.message);
    }
});
}
</script>

<script>
function newWin() {
    var new_window = window.open("../damage_assessment/index.html");
}
</script>

<script>
function submitRule() {    
    var Rules = Parse.Object.extend("Rules5");
    var rules = new Rules();
    var roomId = document.getElementById("room").value;

    var when = document.getElementById("when").value;
    var pFeedBack = document.getElementById("pFeedBack").value;
    var nFeedBack = document.getElementById("nFeedBack").value;
    var pMediaType = document.getElementById("pMediaType").value;
    var nMediaType = document.getElementById("nMediaType").value;

    var minor = document.getElementById("minor").value;
    var delayed = document.getElementById("delayed").value;
    var immediate = document.getElementById("immediate").value;
    var dead = document.getElementById("dead").value;
    var trapped = document.getElementById("trapped").value;

    var gas = document.getElementById("gas").checked? "1":"0";
    var water = document.getElementById("water").checked? "1":"0";
    var elec = document.getElementById("elec").checked? "1":"0";
    var chem = document.getElementById("chem").checked? "1":"0";

    var gas = document.getElementById("gas").checked? "1":"0";
    var water = document.getElementById("water").checked? "1":"0";
    var elec = document.getElementById("elec").checked? "1":"0";
    var chem = document.getElementById("chem").checked? "1":"0";

    var buildingDamage = document.getElementById("bd_none").checked? "0":
     document.getElementById("bd_light").checked?"1":
     document.getElementById("bd_moderate").checked?"2":
     document.getElementById("bd_heavy").checked?"3":"null";

     var fire = document.getElementById("fire_none").checked? "0":
     document.getElementById("fire_smoke").checked?"1":
     document.getElementById("fire_burning").checked?"2":
     document.getElementById("fire_out").checked?"3":"null";

     var road = document.getElementById("unobstructed").checked? "0":
     document.getElementById("oneLane").checked?"1":
     document.getElementById("cyclesOnly").checked?"2":
     document.getElementById("walkOnly").checked?"3":"null"; 

    rules.save({
        RoomId:roomId,
        When:when,
        PFeedBack:pFeedBack,
        PMediaType:pMediaType,
        NFeedBack:nFeedBack,
        NMediaType:nMediaType,
        Minor:minor,
        Delayed:delayed,
        Immediate:immediate,
        Dead:dead,
        Trapped:trapped,
        Gas:gas,
        Water:water,
        Elec:elec,
        Chem:chem,
        BuildingDamage:buildingDamage,
        Fire:fire,
        Road:road
    }, {
      success: function(object) {        
        refreshList();
    }
});
}

function prepare() {
    Parse.initialize("euRVQCTiL5zCMmNZaIo1DXm0dCJLY2jFAZYqLvxb", "lHX3IMCqgQqBLXYvDwGkA2yhdV7NC3lZT3YIxCZJ");
    refreshList();
}
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>

		<title>Assessment Generator</title>
		<!-- Bootstrap -->

		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="css/bootstrap-responsive.css" rel="stylesheet">
		<script src="http://code.jquery.com/jquery-latest.js"></script>		
		<%= stylesheet_link_tag    "bootstrap.css", "bootstrap-responsive.css", :media => "all" %>
		<%= javascript_include_tag "application","bootstrap.js", 'jquery' %>
		<%= csrf_meta_tags %>
	</head>
	<body>		
		<%= yield %>
	</body>
</html>

app/views/rules/_add_form.html.erb
<%= form_for(@rule) do |f| %>
<% if @rule.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

	<ul>
		<% @rule.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="form-inline" >
				<%= f.label "Rule name"%>
				<%= f.text_area :name , :cols => "30", :rows => "1"%>
			</div>
			<br />
			<div class="form-inline" >
				<%= f.label "room #" %>
				<%= f.text_field :roomNo %>
			</div>
			<br />

			<div class="form-inline">
				<%= f.label :when %>
				<%= f.select :when, [['Enter','enter'],['Leave','leave'],['90s','90s']] %>
			</div>
						
			<br />

			<div class="form-inline" >
				<%= f.label "Media Type"%>
				<%= f.select :pMediaType, [['Text','text'],['Picture','picture'],['Video','video']]  %>
				<%= f.label "Feedback" %>
				<%= f.text_area :pFeedback, :cols => "80", :rows => "5"%>
			</div>

			<div class="span12">
				<div class="span2 " >
					<H5>People</H5>
					<div class="form-inline">
						<%= f.number_field :immediate, :min => 0 , :style => "width:30px"%>
						<%= f.label :immediate %>

					</div>
					<div class="form-inline">
						<%= f.number_field :dead , :min => 0 , :style => "width:30px"%>
						<%= f.label :dead %>
					</div>
					<div class="form-inline">
						<%= f.number_field :minor , :min => 0 , :style => "width:30px"%>
						<%= f.label :minor %>
					</div>
					<div class="form-inline">
						<%= f.number_field :dalayed , :min => 0 , :style => "width:30px"%>
						<%= f.label :dalayed %>
					</div>
					<div class="form-inline">
						<%= f.number_field :trapped , :min => 0 , :style => "width:30px"%>
						<%= f.label :trapped %>
					</div>
				</div>

				<div class="span2">
					<H5>Hazard</H5>
					<div class="form-inline">
						<%= f.check_box :water %>
						<%= f.label :water %>
					</div>
					<div class="form-inline">
						<%= f.check_box :chem %>
						<%= f.label :chem %>
					</div>
					<div class="form-inline">
						<%= f.check_box :elec %>
						<%= f.label :elec %>
					</div>
					<div class="form-inline">
						<%= f.check_box :gas %>
						<%= f.label :gas %>
					</div>
				</div>
				<div class="span2" >
					<H5>Building Damage</H5>
					<div class="form-inline">
						<div class="form-inline">
							<%= radio_button_tag(:buildingDamage, "0") %>
							<%= label_tag(:buildingDamage, "None") %>
						</div>
						<div class="form-inline">
							<%= radio_button_tag(:buildingDamage, "1") %>
							<%= label_tag(:buildingDamage, "Light") %>
						</div>
						<div class="form-inline">
							<%= radio_button_tag(:buildingDamage, "2") %>
							<%= label_tag(:buildingDamage, "Moderate") %>
						</div>
						<div class="form-inline">
							<%= radio_button_tag(:buildingDamage, "3") %>
							<%= label_tag(:buildingDamage, "Heavy") %>
						</div>
					</div>
				</div>
				<div class="span3">
					<H5>Road Access</H5>
					<div class="form-inline">
						<div class="form-inline">
							<%= radio_button_tag(:road, "0") %>
							<%= label_tag(:road, "Unobstructed") %>
						</div>
						<div class="form-inline">
							<%= radio_button_tag(:road, "1") %>
							<%= label_tag(:road, "One Lane Open") %>
						</div>
						<div class="form-inline">
							<%= radio_button_tag(:road, "2") %>
							<%= label_tag(:road, "Blocked, Cycles Only") %>
						</div>
						<div class="form-inline">
							<%= radio_button_tag(:road, "3") %>
							<%= label_tag(:road, "Blocked, Walk-in Only") %>
						</div>
					</div>
				</div>
				<div class="span2" >
					<H5>Fire</H5>
					<div class="form-inline">
						<div class="form-inline">
							<%= radio_button_tag(:fire, "0") %>
							<%= label_tag(:fire, "None") %>
						</div>
						<div class="form-inline">
							<%= radio_button_tag(:road, "1") %>
							<%= label_tag(:fire, "Smoke") %>
						</div>
						<div class="form-inline">
							<%= radio_button_tag(:road, "2") %>
							<%= label_tag(:fire, "Burning") %>
						</div>
						<div class="form-inline">
							<%= radio_button_tag(:road, "3") %>
							<%= label_tag(:fire, "Out") %>
						</div>
					</div>
				</div>

			</div>
		</div>

		<div class="form-inline" id="NFeed" style="visibility: hidden">
			<%= f.label "Media Type" %>
			<%= f.select :nMediaType, [['Text','text'],['Picture','picture'],['Video','video']] %>
			<%= f.label "Negative Feedback"%>
			<%= f.text_area :nFeedback , :cols => "30", :rows => "5"%>
		</div>

		<div class="actions">
			<%= f.submit nil, :class => 'btn btn-primary' %>
		</div>

	</div>
</div>

<% end %>

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :roomNo %><br />
    <%= f.text_field :roomNo %>
  </div>
  <div class="field">
    <%= f.label :when %><br />
    <%= f.text_field :when %>
  </div>
  <div class="field">
    <%= f.label :nMediaType %><br />
    <%= f.text_field :nMediaType %>
  </div>
  <div class="field">
    <%= f.label :nFeedback %><br />
    <%= f.text_field :nFeedback %>
  </div>
  <div class="field">
    <%= f.label :pMediaType %><br />
    <%= f.text_field :pMediaType %>
  </div>
  <div class="field">
    <%= f.label :pFeedback %><br />
    <%= f.text_field :pFeedback %>
  </div>
  <div class="field">
    <%= f.label :buildingDamage %><br />
    <%= f.number_field :buildingDamage %>
  </div>
  <div class="field">
    <%= f.label :road %><br />
    <%= f.number_field :road %>
  </div>
  <div class="field">
    <%= f.label :fire %><br />
    <%= f.number_field :fire %>
  </div>
  <div class="field">
    <%= f.label :water %><br />
    <%= f.check_box :water %>
  </div>
  <div class="field">
    <%= f.label :chem %><br />
    <%= f.check_box :chem %>
  </div>
  <div class="field">
    <%= f.label :elec %><br />
    <%= f.check_box :elec %>
  </div>
  <div class="field">
    <%= f.label :gas %><br />
    <%= f.check_box :gas %>
  </div>
  <div class="field">
    <%= f.label :immediate %><br />
    <%= f.number_field :immediate %>
  </div>
  <div class="field">
    <%= f.label :dead %><br />
    <%= f.number_field :dead %>
  </div>
  <div class="field">
    <%= f.label :minor %><br />
    <%= f.number_field :minor %>
  </div>
  <div class="field">
    <%= f.label :dalayed %><br />
    <%= f.number_field :dalayed %>
  </div>
  <div class="field">
    <%= f.label :trapped %><br />
    <%= f.number_field :trapped %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/edit.html.erb
<div class="page-header">
	<h1><%= t 'Editing rule'%></h1>
</div>
<%= render 'add_form' %>
<div class="form-actions">
	<%= link_to 'Show', @rule, :class => 'btn' %> |
	<%= link_to 'Back', rules_path, :class => 'btn' %>
</div>

app/views/rules/index.html.erb
<div class="page-header">
  <h1><%=t 'List of Rules'%></h1>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Roomno</th>
			<th>When</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @rules.each do |rule| %>
		<tr>
			<td><%= rule.name %></td>
			<td><%= rule.roomNo %></td>
			<td><%= rule.when %></td>
			<td> <%= link_to t('.show', :default => t("helpers.links.show")),
			rule, :class => 'btn btn-mini btn-success' %>
			<%= link_to t('.edit', :default => t("helpers.links.edit")),
			edit_rule_path(rule), :class => 'btn btn-mini' %>
			<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
			rule, method: :delete,
			:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
			:class => 'btn btn-mini btn-danger' %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to t('.new'),
new_rule_path,
:class => 'btn btn-primary' %>

app/views/rules/new.html.erb
<div class="page-header">
	<h1><%= t 'New Rule'%></h1>
</div>
<%= render :partial =>'add_form' %>
<div class="form-actions">
	<%= link_to 'Back', rules_path, :class => 'btn' %>
</div>

app/views/rules/show.html.erb
<div class="page-header">
	<h1><%= t 'Show rule'%></h1>
</div>
<p id="notice">
	<%= notice %>
</p>
<dl class="dl-horizontal">

	<dt>
		<strong>Name:</strong>
	</dt>
	<dd>
		<%= @rule.name %>
	</dd>

	<dt>
		<strong>Roomno:</strong>
	</dt>
	<dd>
		<%= @rule.roomNo %>
	</dd>

	<dt>
		<strong>When:</strong>
	</dt>
	<dd>
		<%= @rule.when %>
	</dd>

	<dt>
		<strong>Nmediatype:</strong>
	</dt>
	<dd>
		<%= @rule.nMediaType %>
	</dd>

	<dt>
		<strong>Nfeedback:</strong>
	</dt>
	<dd>
		<%= @rule.nFeedback %>
	</dd>

	<dt>
		<strong>Pmediatype:</strong>
	</dt>
	<dd>
		<%= @rule.pMediaType %>
	</dd>

	<dt>
		<strong>Pfeedback:</strong>
	</dt>
	<dd>
		<%= @rule.pFeedback %>
	</dd>

	<dt>
		<strong>Buildingdamage:</strong>
	</dt>
	<dd>
		<%= @rule.buildingDamage %>
	</dd>

	<dt>
		<strong>Road:</strong>
	</dt>
	<dd>
		<%= @rule.road %>
	</dd>

	<dt>
		<strong>Fire:</strong>
	</dt>
	<dd>
		<%= @rule.fire %>
	</dd>

	<dt>
		<strong>Water:</strong>
	</dt>
	<dd>
		<%= @rule.water %>
	</dd>

	<dt>
		<strong>Chem:</strong>
	</dt>
	<dd>
		<%= @rule.chem %>
	</dd>

	<dt>
		<strong>Elec:</strong>
	</dt>
	<dd>
		<%= @rule.elec %>
	</dd>

	<dt>
		<strong>Gas:</strong>
	</dt>
	<dd>
		<%= @rule.gas %>
	</dd>

	<dt>
		<strong>Immediate:</strong>
	</dt>
	<dd>
		<%= @rule.immediate %>
	</dd>

	<dt>
		<strong>Dead:</strong>
	</dt>
	<dd>
		<%= @rule.dead %>
	</dd>

	<dt>
		<strong>Minor:</strong>
	</dt>
	<dd>
		<%= @rule.minor %>
	</dd>

	<dt>
		<strong>Dalayed:</strong>
	</dt>
	<dd>
		<%= @rule.dalayed %>
	</dd>

	<dt>
		<strong>Trapped:</strong>
	</dt>
	<dd>
		<%= @rule.trapped %>
	</dd>
</dl>
<div class="form-actions">
	<%= link_to t('.back', :default => t("helpers.links.back")),
	rules_path, :class => 'btn'  %>
	<%= link_to t('.edit', :default => t("helpers.links.edit")),
	edit_rule_path(@rule), :class => 'btn' %>

</div>